image: ruby:2.7.1

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      bundle install 
      bin/rails db:migrate
      bin/rails db:seed      
    command: bin/rails s -p 3001

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3001
    onOpen: notify
